### ISSUE TITLE
SRCNN IMAGE

### ISSUE THREAD

**Issue by kairos03** [Dcom-KHU/2019-DeepLearning-SuperResolution#1]

**Comment by tnt-ooo-tnt** [comment]
![fig9](https://user-images.githubusercontent.com/39299372/51464628-5a1c6680-1da9-11e9-96cf-5751a6636320.PNG)
![fig10](https://user-images.githubusercontent.com/39299372/51464629-5a1c6680-1da9-11e9-881a-94a082a65470.PNG)
![fig11](https://user-images.githubusercontent.com/39299372/51464630-5ab4fd00-1da9-11e9-83dc-ced351b2ea74.PNG)
![fig12](https://user-images.githubusercontent.com/39299372/51464631-5b4d9380-1da9-11e9-8f96-f2207912188d.PNG)
![fig13](https://user-images.githubusercontent.com/39299372/51464633-5b4d9380-1da9-11e9-9148-cbd37fabdaf1.PNG)
![table1](https://user-images.githubusercontent.com/39299372/51464635-5b4d9380-1da9-11e9-8198-731cd7903b2f.PNG)
![table5](https://user-images.githubusercontent.com/39299372/51464636-5be62a00-1da9-11e9-830f-b6e377d96ee1.PNG)
![table234](https://user-images.githubusercontent.com/39299372/51464638-5be62a00-1da9-11e9-9834-d3f962b74230.PNG)
![fig4](https://user-images.githubusercontent.com/39299372/51464641-5be62a00-1da9-11e9-9c60-29ee0a9a898f.PNG)
![fig5](https://user-images.githubusercontent.com/39299372/51464642-5c7ec080-1da9-11e9-9361-d66ac6671df6.PNG)
![fig6](https://user-images.githubusercontent.com/39299372/51464643-5c7ec080-1da9-11e9-8728-ad9f284b5bd3.PNG)
![fig7](https://user-images.githubusercontent.com/39299372/51464644-5d175700-1da9-11e9-988f-91ab18f3cd81.PNG)
![fig8](https://user-images.githubusercontent.com/39299372/51464645-5d175700-1da9-11e9-852b-b9d845aecf58.PNG)
