### ISSUE TITLE
ESPCN 논문에서의 이해하지 못한점.

### ISSUE THREAD

**Issue by JunjaK** [Dcom-KHU/2019-DeepLearning-SuperResolution#4]
19.1.23 ESPCN 논문 분석 중 이해하지 못한 점을 올립니다.(공유된 것 포함)
1. PS(periodic shuffle)의 연산에 관련된 것
  - mod(ks, r) = 0이 되는 이유
  - kl = ks/r 이 되는 이유
  - WL = nL-1 * nL * kL * kL = nL-1 * (r^2*C) * kL * kL 에서 nL = r^2*C가 되는 이유 / (참고 : n0 = C) 

2. ESPCN 모델에서 sub-pixel convolution layer를 거쳐 HR output이 나오는 과정에서 학습이 일어나는지에 대한 여부(그 이유도...)

**Comment by kairos03** [comment]
2. 
https://github.com/tetrachrome/subpixel readme를 참고하자면 
![image](https://user-images.githubusercontent.com/6357456/51651254-8fee6480-1fce-11e9-92e4-acdb4dbd1727.png)
PS연산의 수식은 위와 같고
numpy로 구현하면 
```python
def PS(I, r):
  assert len(I.shape) == 3
  assert r>0
  r = int(r)
  O = np.zeros((I.shape[0]*r, I.shape[1]*r, I.shape[2]/(r*2)))
  for x in range(O.shape[0]):
    for y in range(O.shape[1]):
      for c in range(O.shape[2]):
        c += 1
        a = np.floor(x/r).astype("int")
        b = np.floor(y/r).astype("int")
        d = c*r*(y%r) + c*(x%r)
        print a, b, d
        O[x, y, c-1] = I[a, b, d]
  return O
```
위와 같습니다. 학습할 수 있는 파라미터가 없죠? 

PS자체는 Convolution이 없지만

PS Conv layer는 PS입력 크기를 맞추기위해 
```
이전 층 출력 => conv => PS => 출력
```
을 해서 이름을 PS Conv라고 지은것 같습니다.
